### ISSUE TITLE
Facing below issue while executing the eval script of LiteFlowNet2-TF2

### ISSUE THREAD

**Issue by thisiskiru** [rogerhcheng/LiteFlowNet2-TF2#1]
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    flow_color = flow_to_color(flow, convert_to_bgr=False)
  File "D:\Dataset\LiteFlowNet2-TF2-master\draw_flow.py", line 124, in flow_to_color
    return flow_compute_color(u, v, convert_to_bgr)
  File "D:\Dataset\LiteFlowNet2-TF2-master\draw_flow.py", line 83, in flow_compute_color
    col0 = tmp[k0] / 255.0
IndexError: index -2147483648 is out of bounds for axis 0 with size 55

**Comment by rogerhcheng** [comment]
Sorry, I don't see this problem on my machine.  Can you give information on the machine and platform that you're using?

**Comment by thisiskiru** [comment]
oh sorry..... I am working on.....
windows 10 (version-1909)
intel i7-2630QM @2.00 GHz
8GB ram
python 3.7 
Tensorflow 2.2 
tensorflow_addons==0.10.0

**Comment by rogerhcheng** [comment]
OK, I find that this occurs if I disable GPU support on my machine and force TensorFlow to run in CPU mode.  Are you running in CPU mode?  If so, then unfortunately I don't have the time right now to try to get the code working in CPU mode.

**Comment by thisiskiru** [comment]
actually im working with CPU if that so.
