### ISSUE TITLE
Would you please give direction how I could use LiteflowNet2 as sub module in tf.keras

### ISSUE THREAD

**Issue by thisiskiru** [rogerhcheng/LiteFlowNet2-TF2#2]
I was looking to use this model for temporal extractor between frames in image translation. frankly im pretty new to TensorFlow. 
im trying to pass two tensor variables for LiteflowNet() class but this raise is only supported inside of tf.function or when eager execution is enabled.

**Comment by rogerhcheng** [comment]
I am planning on making the code compatible with eager execution, but haven't had the time to do that yet.

**Comment by maheeeetaaa** [comment]
@rogerhcheng  hello, I just tried to run your code and faced this issue: 

If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "eval.py", line 72, in <module>
    flow_color = flow_to_color(flow, convert_to_bgr=False)
  File "/content/LiteFlowNet2-TF2/draw_flow.py", line 124, in flow_to_color
    return flow_compute_color(u, v, convert_to_bgr)
  File "/content/LiteFlowNet2-TF2/draw_flow.py", line 83, in flow_compute_color
    col0 = tmp[k0] / 255.0
IndexError: index -2147483648 is out of bounds for axis 0 with size 55


I am very new in this topic and dont know how to fix this. Can you please tell me how i can fix this and why I get this error?

**Comment by rogerhcheng** [comment]
You will get that error if you run in CPU mode.  Right now this code only works in GPU mode.  Sorry about that.
