### ISSUE TITLE
flow returns all nans on CPU

### ISSUE THREAD

**Issue by dirkpitt2050** [rogerhcheng/LiteFlowNet2-TF2#3]
Using the same command as in the README:
`python eval.py --img1=./images/first.png --img2=./images/second.png --use_Sintel=True --display_flow=True --img_out=out.png`

I get a **flow result with all nans**. Why?

Same for `--use_Sintel=False`. Basically the same result as this LiteFlowNet issue: keeper121/liteflownet-tf2#7

I am running TensorFlow 2.2.0, addons 0.10.0, Python 3.8.5, Pillow 8.0.1.

**Comment by dirkpitt2050** [comment]
I tried this repo in Google Colab with a GPU runtime and it works there.
If I change the Colab runtime to CPU then it gives nans.

So the issue has to do with running on CPU...

FYI the tf.train.import_meta_graph clear_device=True trick won't work as there are no .meta files in the pretained models folder...

**Comment by rogerhcheng** [comment]
Unfortunately I don't have the time right now to make the code compatible with CPU mode.
